version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    actions:
      patterns:
        - actions/*
  schedule:
    interval: monthly
    time: "06:30"
    timezone: Europe/London
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: monthly
    time: "06:30"
    timezone: Europe/London
